# Generated by Django 6.0.3 on 2026-04-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resignations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resignation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='resignation',
            name='admin_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
