# Generated by Django 6.0.3 on 2026-04-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resignations', '0002_remove_resignation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignation',
            name='exit_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='resignation_letter',
            field=models.FileField(blank=True, null=True, upload_to='resignation_letters/'),
        ),
    ]
