# Generated by Django 6.0.3 on 2026-04-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resignations', '0003_resignation_exit_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignation',
            name='current_stage',
            field=models.CharField(default='Submitted', max_length=50),
        ),
        migrations.AddField(
            model_name='resignation',
            name='next_role',
            field=models.CharField(default='Manager', max_length=50),
        ),
    ]
