# Generated by Django 6.0.3 on 2026-04-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_asset_returned_on_asset_assigned_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned'), ('Lost', 'Lost')], default='Issued', max_length=20),
        ),
    ]
