# Generated by Django 6.0.3 on 2026-05-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_is_returned_asset_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='asset',
            name='manager_approval',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='manager_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
