# Generated by Django 6.0.3 on 2026-06-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hod',
        ),
    ]
