# Generated by Django 6.0.3 on 2026-04-05 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('resignations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared'), ('Issues', 'Issues')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='resignations.resignation')),
            ],
        ),
    ]
