# Generated by Django 6.0.3 on 2026-04-05 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0001_initial'),
        ('resignations', '0002_remove_resignation_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Library', 'Library')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='resignations.resignation')),
            ],
            options={
                'unique_together': {('resignation', 'department_name')},
            },
        ),
        migrations.DeleteModel(
            name='ClearanceChecklist',
        ),
    ]
