# Generated by Django 6.0.3 on 2026-04-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0002_clearance_delete_clearancechecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
